### ISSUE TITLE
Can you re upload pubfogl please?

### ISSUE THREAD

**Issue by Owned67** [mvandorp/server-addons#1]
hello,

Can you re upload pubfogl please?

Cheers,

**Comment by mvandorp** [comment]
Hi Owned. Sorry, I haven't been paying attention lately. The 'pubfogl' config I uploaded was just a quick attempt by me to put a pubfogl config together, but it didn't work and I haven't bothered to finish it, which is why I have removed it again. You are better off looking elsewhere a config like that, though I wasn't able to find much myself which is why I tried making my own.

**Comment by Owned67** [comment]
hey, ok np
